/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebpToJpgRouteImport } from './routes/webp-to-jpg'
import { Route as WatermarkPdfRouteImport } from './routes/watermark-pdf'
import { Route as WatermarkImageRouteImport } from './routes/watermark-image'
import { Route as TextToPdfRouteImport } from './routes/text-to-pdf'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as RotatePdfRouteImport } from './routes/rotate-pdf'
import { Route as RotateImageRouteImport } from './routes/rotate-image'
import { Route as ResizeImageRouteImport } from './routes/resize-image'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PngToJpgRouteImport } from './routes/png-to-jpg'
import { Route as PdfToJpgRouteImport } from './routes/pdf-to-jpg'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as JpgToPngRouteImport } from './routes/jpg-to-png'
import { Route as JpgToPdfRouteImport } from './routes/jpg-to-pdf'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ExcelToPdfRouteImport } from './routes/excel-to-pdf'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CropImageRouteImport } from './routes/crop-image'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as CompressImageRouteImport } from './routes/compress-image'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWhyCompressPdfsForEmailRouteImport } from './routes/blog/why-compress-pdfs-for-email'
import { Route as BlogWhatIsClientSideProcessingRouteImport } from './routes/blog/what-is-client-side-processing'
import { Route as BlogWebpVsJpgVsPngRouteImport } from './routes/blog/webp-vs-jpg-vs-png'
import { Route as BlogTextToPdfConverterGuideRouteImport } from './routes/blog/text-to-pdf-converter-guide'
import { Route as BlogRisksOfOnlineFileConvertersRouteImport } from './routes/blog/risks-of-online-file-converters'
import { Route as BlogPdfVsWordDifferencesRouteImport } from './routes/blog/pdf-vs-word-differences'
import { Route as BlogJpgVsPngGuideRouteImport } from './routes/blog/jpg-vs-png-guide'
import { Route as BlogImageAspectRatioCroppingGuideRouteImport } from './routes/blog/image-aspect-ratio-cropping-guide'
import { Route as BlogHowToWatermarkPhotosOnlineRouteImport } from './routes/blog/how-to-watermark-photos-online'
import { Route as BlogHowToWatermarkPdfDocumentsRouteImport } from './routes/blog/how-to-watermark-pdf-documents'
import { Route as BlogHowToSplitPdfPagesRouteImport } from './routes/blog/how-to-split-pdf-pages'
import { Route as BlogHowToRotatePdfPagesRouteImport } from './routes/blog/how-to-rotate-pdf-pages'
import { Route as BlogHowToResizeImagesSocialMediaRouteImport } from './routes/blog/how-to-resize-images-social-media'
import { Route as BlogHowToMergePdfFilesOnlineRouteImport } from './routes/blog/how-to-merge-pdf-files-online'
import { Route as BlogHowToConvertWebpToJpgRouteImport } from './routes/blog/how-to-convert-webp-to-jpg'
import { Route as BlogHowToConvertPdfToWordRouteImport } from './routes/blog/how-to-convert-pdf-to-word'
import { Route as BlogHowToConvertImagesToPdfRouteImport } from './routes/blog/how-to-convert-images-to-pdf'
import { Route as BlogHowToCheckPdfConverterSafetyRouteImport } from './routes/blog/how-to-check-pdf-converter-safety'
import { Route as BlogFreelanceContractManagementFreeRouteImport } from './routes/blog/freelance-contract-management-free'
import { Route as BlogExcelToPdfFormattingGuideRouteImport } from './routes/blog/excel-to-pdf-formatting-guide'
import { Route as BlogDigitalDocumentWorkflowStudentsRouteImport } from './routes/blog/digital-document-workflow-students'
import { Route as BlogCompressPdfWithoutLosingQualityRouteImport } from './routes/blog/compress-pdf-without-losing-quality'
import { Route as BlogBrowserTechReplacingDesktopAppsRouteImport } from './routes/blog/browser-tech-replacing-desktop-apps'
import { Route as BlogBrowserPdfConverterPrivacyRouteImport } from './routes/blog/browser-pdf-converter-privacy'
import { Route as BlogBestFreePdfToolsRouteImport } from './routes/blog/best-free-pdf-tools'
import { Route as BlogBatchImageProcessingGuideRouteImport } from './routes/blog/batch-image-processing-guide'

const WebpToJpgRoute = WebpToJpgRouteImport.update({
  id: '/webp-to-jpg',
  path: '/webp-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkPdfRoute = WatermarkPdfRouteImport.update({
  id: '/watermark-pdf',
  path: '/watermark-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkImageRoute = WatermarkImageRouteImport.update({
  id: '/watermark-image',
  path: '/watermark-image',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToPdfRoute = TextToPdfRouteImport.update({
  id: '/text-to-pdf',
  path: '/text-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatePdfRoute = RotatePdfRouteImport.update({
  id: '/rotate-pdf',
  path: '/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RotateImageRoute = RotateImageRouteImport.update({
  id: '/rotate-image',
  path: '/rotate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeImageRoute = ResizeImageRouteImport.update({
  id: '/resize-image',
  path: '/resize-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToJpgRoute = PngToJpgRouteImport.update({
  id: '/png-to-jpg',
  path: '/png-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToJpgRoute = PdfToJpgRouteImport.update({
  id: '/pdf-to-jpg',
  path: '/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPngRoute = JpgToPngRouteImport.update({
  id: '/jpg-to-png',
  path: '/jpg-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPdfRoute = JpgToPdfRouteImport.update({
  id: '/jpg-to-pdf',
  path: '/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelToPdfRoute = ExcelToPdfRouteImport.update({
  id: '/excel-to-pdf',
  path: '/excel-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CropImageRoute = CropImageRouteImport.update({
  id: '/crop-image',
  path: '/crop-image',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressImageRoute = CompressImageRouteImport.update({
  id: '/compress-image',
  path: '/compress-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhyCompressPdfsForEmailRoute =
  BlogWhyCompressPdfsForEmailRouteImport.update({
    id: '/blog/why-compress-pdfs-for-email',
    path: '/blog/why-compress-pdfs-for-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhatIsClientSideProcessingRoute =
  BlogWhatIsClientSideProcessingRouteImport.update({
    id: '/blog/what-is-client-side-processing',
    path: '/blog/what-is-client-side-processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWebpVsJpgVsPngRoute = BlogWebpVsJpgVsPngRouteImport.update({
  id: '/blog/webp-vs-jpg-vs-png',
  path: '/blog/webp-vs-jpg-vs-png',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTextToPdfConverterGuideRoute =
  BlogTextToPdfConverterGuideRouteImport.update({
    id: '/blog/text-to-pdf-converter-guide',
    path: '/blog/text-to-pdf-converter-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRisksOfOnlineFileConvertersRoute =
  BlogRisksOfOnlineFileConvertersRouteImport.update({
    id: '/blog/risks-of-online-file-converters',
    path: '/blog/risks-of-online-file-converters',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogPdfVsWordDifferencesRoute =
  BlogPdfVsWordDifferencesRouteImport.update({
    id: '/blog/pdf-vs-word-differences',
    path: '/blog/pdf-vs-word-differences',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogJpgVsPngGuideRoute = BlogJpgVsPngGuideRouteImport.update({
  id: '/blog/jpg-vs-png-guide',
  path: '/blog/jpg-vs-png-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogImageAspectRatioCroppingGuideRoute =
  BlogImageAspectRatioCroppingGuideRouteImport.update({
    id: '/blog/image-aspect-ratio-cropping-guide',
    path: '/blog/image-aspect-ratio-cropping-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToWatermarkPhotosOnlineRoute =
  BlogHowToWatermarkPhotosOnlineRouteImport.update({
    id: '/blog/how-to-watermark-photos-online',
    path: '/blog/how-to-watermark-photos-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToWatermarkPdfDocumentsRoute =
  BlogHowToWatermarkPdfDocumentsRouteImport.update({
    id: '/blog/how-to-watermark-pdf-documents',
    path: '/blog/how-to-watermark-pdf-documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToSplitPdfPagesRoute = BlogHowToSplitPdfPagesRouteImport.update({
  id: '/blog/how-to-split-pdf-pages',
  path: '/blog/how-to-split-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToRotatePdfPagesRoute = BlogHowToRotatePdfPagesRouteImport.update({
  id: '/blog/how-to-rotate-pdf-pages',
  path: '/blog/how-to-rotate-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToResizeImagesSocialMediaRoute =
  BlogHowToResizeImagesSocialMediaRouteImport.update({
    id: '/blog/how-to-resize-images-social-media',
    path: '/blog/how-to-resize-images-social-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToMergePdfFilesOnlineRoute =
  BlogHowToMergePdfFilesOnlineRouteImport.update({
    id: '/blog/how-to-merge-pdf-files-online',
    path: '/blog/how-to-merge-pdf-files-online',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToConvertWebpToJpgRoute =
  BlogHowToConvertWebpToJpgRouteImport.update({
    id: '/blog/how-to-convert-webp-to-jpg',
    path: '/blog/how-to-convert-webp-to-jpg',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToConvertPdfToWordRoute =
  BlogHowToConvertPdfToWordRouteImport.update({
    id: '/blog/how-to-convert-pdf-to-word',
    path: '/blog/how-to-convert-pdf-to-word',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToConvertImagesToPdfRoute =
  BlogHowToConvertImagesToPdfRouteImport.update({
    id: '/blog/how-to-convert-images-to-pdf',
    path: '/blog/how-to-convert-images-to-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogHowToCheckPdfConverterSafetyRoute =
  BlogHowToCheckPdfConverterSafetyRouteImport.update({
    id: '/blog/how-to-check-pdf-converter-safety',
    path: '/blog/how-to-check-pdf-converter-safety',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFreelanceContractManagementFreeRoute =
  BlogFreelanceContractManagementFreeRouteImport.update({
    id: '/blog/freelance-contract-management-free',
    path: '/blog/freelance-contract-management-free',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogExcelToPdfFormattingGuideRoute =
  BlogExcelToPdfFormattingGuideRouteImport.update({
    id: '/blog/excel-to-pdf-formatting-guide',
    path: '/blog/excel-to-pdf-formatting-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDigitalDocumentWorkflowStudentsRoute =
  BlogDigitalDocumentWorkflowStudentsRouteImport.update({
    id: '/blog/digital-document-workflow-students',
    path: '/blog/digital-document-workflow-students',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCompressPdfWithoutLosingQualityRoute =
  BlogCompressPdfWithoutLosingQualityRouteImport.update({
    id: '/blog/compress-pdf-without-losing-quality',
    path: '/blog/compress-pdf-without-losing-quality',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBrowserTechReplacingDesktopAppsRoute =
  BlogBrowserTechReplacingDesktopAppsRouteImport.update({
    id: '/blog/browser-tech-replacing-desktop-apps',
    path: '/blog/browser-tech-replacing-desktop-apps',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBrowserPdfConverterPrivacyRoute =
  BlogBrowserPdfConverterPrivacyRouteImport.update({
    id: '/blog/browser-pdf-converter-privacy',
    path: '/blog/browser-pdf-converter-privacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBestFreePdfToolsRoute = BlogBestFreePdfToolsRouteImport.update({
  id: '/blog/best-free-pdf-tools',
  path: '/blog/best-free-pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBatchImageProcessingGuideRoute =
  BlogBatchImageProcessingGuideRouteImport.update({
    id: '/blog/batch-image-processing-guide',
    path: '/blog/batch-image-processing-guide',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/crop-image': typeof CropImageRoute
  '/disclaimer': typeof DisclaimerRoute
  '/excel-to-pdf': typeof ExcelToPdfRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/merge-pdf': typeof MergePdfRoute
  '/mission': typeof MissionRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/privacy': typeof PrivacyRoute
  '/resize-image': typeof ResizeImageRoute
  '/rotate-image': typeof RotateImageRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/text-to-pdf': typeof TextToPdfRoute
  '/watermark-image': typeof WatermarkImageRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/webp-to-jpg': typeof WebpToJpgRoute
  '/blog/batch-image-processing-guide': typeof BlogBatchImageProcessingGuideRoute
  '/blog/best-free-pdf-tools': typeof BlogBestFreePdfToolsRoute
  '/blog/browser-pdf-converter-privacy': typeof BlogBrowserPdfConverterPrivacyRoute
  '/blog/browser-tech-replacing-desktop-apps': typeof BlogBrowserTechReplacingDesktopAppsRoute
  '/blog/compress-pdf-without-losing-quality': typeof BlogCompressPdfWithoutLosingQualityRoute
  '/blog/digital-document-workflow-students': typeof BlogDigitalDocumentWorkflowStudentsRoute
  '/blog/excel-to-pdf-formatting-guide': typeof BlogExcelToPdfFormattingGuideRoute
  '/blog/freelance-contract-management-free': typeof BlogFreelanceContractManagementFreeRoute
  '/blog/how-to-check-pdf-converter-safety': typeof BlogHowToCheckPdfConverterSafetyRoute
  '/blog/how-to-convert-images-to-pdf': typeof BlogHowToConvertImagesToPdfRoute
  '/blog/how-to-convert-pdf-to-word': typeof BlogHowToConvertPdfToWordRoute
  '/blog/how-to-convert-webp-to-jpg': typeof BlogHowToConvertWebpToJpgRoute
  '/blog/how-to-merge-pdf-files-online': typeof BlogHowToMergePdfFilesOnlineRoute
  '/blog/how-to-resize-images-social-media': typeof BlogHowToResizeImagesSocialMediaRoute
  '/blog/how-to-rotate-pdf-pages': typeof BlogHowToRotatePdfPagesRoute
  '/blog/how-to-split-pdf-pages': typeof BlogHowToSplitPdfPagesRoute
  '/blog/how-to-watermark-pdf-documents': typeof BlogHowToWatermarkPdfDocumentsRoute
  '/blog/how-to-watermark-photos-online': typeof BlogHowToWatermarkPhotosOnlineRoute
  '/blog/image-aspect-ratio-cropping-guide': typeof BlogImageAspectRatioCroppingGuideRoute
  '/blog/jpg-vs-png-guide': typeof BlogJpgVsPngGuideRoute
  '/blog/pdf-vs-word-differences': typeof BlogPdfVsWordDifferencesRoute
  '/blog/risks-of-online-file-converters': typeof BlogRisksOfOnlineFileConvertersRoute
  '/blog/text-to-pdf-converter-guide': typeof BlogTextToPdfConverterGuideRoute
  '/blog/webp-vs-jpg-vs-png': typeof BlogWebpVsJpgVsPngRoute
  '/blog/what-is-client-side-processing': typeof BlogWhatIsClientSideProcessingRoute
  '/blog/why-compress-pdfs-for-email': typeof BlogWhyCompressPdfsForEmailRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/crop-image': typeof CropImageRoute
  '/disclaimer': typeof DisclaimerRoute
  '/excel-to-pdf': typeof ExcelToPdfRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/merge-pdf': typeof MergePdfRoute
  '/mission': typeof MissionRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/privacy': typeof PrivacyRoute
  '/resize-image': typeof ResizeImageRoute
  '/rotate-image': typeof RotateImageRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/text-to-pdf': typeof TextToPdfRoute
  '/watermark-image': typeof WatermarkImageRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/webp-to-jpg': typeof WebpToJpgRoute
  '/blog/batch-image-processing-guide': typeof BlogBatchImageProcessingGuideRoute
  '/blog/best-free-pdf-tools': typeof BlogBestFreePdfToolsRoute
  '/blog/browser-pdf-converter-privacy': typeof BlogBrowserPdfConverterPrivacyRoute
  '/blog/browser-tech-replacing-desktop-apps': typeof BlogBrowserTechReplacingDesktopAppsRoute
  '/blog/compress-pdf-without-losing-quality': typeof BlogCompressPdfWithoutLosingQualityRoute
  '/blog/digital-document-workflow-students': typeof BlogDigitalDocumentWorkflowStudentsRoute
  '/blog/excel-to-pdf-formatting-guide': typeof BlogExcelToPdfFormattingGuideRoute
  '/blog/freelance-contract-management-free': typeof BlogFreelanceContractManagementFreeRoute
  '/blog/how-to-check-pdf-converter-safety': typeof BlogHowToCheckPdfConverterSafetyRoute
  '/blog/how-to-convert-images-to-pdf': typeof BlogHowToConvertImagesToPdfRoute
  '/blog/how-to-convert-pdf-to-word': typeof BlogHowToConvertPdfToWordRoute
  '/blog/how-to-convert-webp-to-jpg': typeof BlogHowToConvertWebpToJpgRoute
  '/blog/how-to-merge-pdf-files-online': typeof BlogHowToMergePdfFilesOnlineRoute
  '/blog/how-to-resize-images-social-media': typeof BlogHowToResizeImagesSocialMediaRoute
  '/blog/how-to-rotate-pdf-pages': typeof BlogHowToRotatePdfPagesRoute
  '/blog/how-to-split-pdf-pages': typeof BlogHowToSplitPdfPagesRoute
  '/blog/how-to-watermark-pdf-documents': typeof BlogHowToWatermarkPdfDocumentsRoute
  '/blog/how-to-watermark-photos-online': typeof BlogHowToWatermarkPhotosOnlineRoute
  '/blog/image-aspect-ratio-cropping-guide': typeof BlogImageAspectRatioCroppingGuideRoute
  '/blog/jpg-vs-png-guide': typeof BlogJpgVsPngGuideRoute
  '/blog/pdf-vs-word-differences': typeof BlogPdfVsWordDifferencesRoute
  '/blog/risks-of-online-file-converters': typeof BlogRisksOfOnlineFileConvertersRoute
  '/blog/text-to-pdf-converter-guide': typeof BlogTextToPdfConverterGuideRoute
  '/blog/webp-vs-jpg-vs-png': typeof BlogWebpVsJpgVsPngRoute
  '/blog/what-is-client-side-processing': typeof BlogWhatIsClientSideProcessingRoute
  '/blog/why-compress-pdfs-for-email': typeof BlogWhyCompressPdfsForEmailRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compress-image': typeof CompressImageRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/cookie': typeof CookieRoute
  '/crop-image': typeof CropImageRoute
  '/disclaimer': typeof DisclaimerRoute
  '/excel-to-pdf': typeof ExcelToPdfRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/merge-pdf': typeof MergePdfRoute
  '/mission': typeof MissionRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/privacy': typeof PrivacyRoute
  '/resize-image': typeof ResizeImageRoute
  '/rotate-image': typeof RotateImageRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/text-to-pdf': typeof TextToPdfRoute
  '/watermark-image': typeof WatermarkImageRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/webp-to-jpg': typeof WebpToJpgRoute
  '/blog/batch-image-processing-guide': typeof BlogBatchImageProcessingGuideRoute
  '/blog/best-free-pdf-tools': typeof BlogBestFreePdfToolsRoute
  '/blog/browser-pdf-converter-privacy': typeof BlogBrowserPdfConverterPrivacyRoute
  '/blog/browser-tech-replacing-desktop-apps': typeof BlogBrowserTechReplacingDesktopAppsRoute
  '/blog/compress-pdf-without-losing-quality': typeof BlogCompressPdfWithoutLosingQualityRoute
  '/blog/digital-document-workflow-students': typeof BlogDigitalDocumentWorkflowStudentsRoute
  '/blog/excel-to-pdf-formatting-guide': typeof BlogExcelToPdfFormattingGuideRoute
  '/blog/freelance-contract-management-free': typeof BlogFreelanceContractManagementFreeRoute
  '/blog/how-to-check-pdf-converter-safety': typeof BlogHowToCheckPdfConverterSafetyRoute
  '/blog/how-to-convert-images-to-pdf': typeof BlogHowToConvertImagesToPdfRoute
  '/blog/how-to-convert-pdf-to-word': typeof BlogHowToConvertPdfToWordRoute
  '/blog/how-to-convert-webp-to-jpg': typeof BlogHowToConvertWebpToJpgRoute
  '/blog/how-to-merge-pdf-files-online': typeof BlogHowToMergePdfFilesOnlineRoute
  '/blog/how-to-resize-images-social-media': typeof BlogHowToResizeImagesSocialMediaRoute
  '/blog/how-to-rotate-pdf-pages': typeof BlogHowToRotatePdfPagesRoute
  '/blog/how-to-split-pdf-pages': typeof BlogHowToSplitPdfPagesRoute
  '/blog/how-to-watermark-pdf-documents': typeof BlogHowToWatermarkPdfDocumentsRoute
  '/blog/how-to-watermark-photos-online': typeof BlogHowToWatermarkPhotosOnlineRoute
  '/blog/image-aspect-ratio-cropping-guide': typeof BlogImageAspectRatioCroppingGuideRoute
  '/blog/jpg-vs-png-guide': typeof BlogJpgVsPngGuideRoute
  '/blog/pdf-vs-word-differences': typeof BlogPdfVsWordDifferencesRoute
  '/blog/risks-of-online-file-converters': typeof BlogRisksOfOnlineFileConvertersRoute
  '/blog/text-to-pdf-converter-guide': typeof BlogTextToPdfConverterGuideRoute
  '/blog/webp-vs-jpg-vs-png': typeof BlogWebpVsJpgVsPngRoute
  '/blog/what-is-client-side-processing': typeof BlogWhatIsClientSideProcessingRoute
  '/blog/why-compress-pdfs-for-email': typeof BlogWhyCompressPdfsForEmailRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compress-image'
    | '/compress-pdf'
    | '/contact'
    | '/cookie'
    | '/crop-image'
    | '/disclaimer'
    | '/excel-to-pdf'
    | '/how-it-works'
    | '/jpg-to-pdf'
    | '/jpg-to-png'
    | '/merge-pdf'
    | '/mission'
    | '/pdf-to-jpg'
    | '/png-to-jpg'
    | '/privacy'
    | '/resize-image'
    | '/rotate-image'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/terms'
    | '/text-to-pdf'
    | '/watermark-image'
    | '/watermark-pdf'
    | '/webp-to-jpg'
    | '/blog/batch-image-processing-guide'
    | '/blog/best-free-pdf-tools'
    | '/blog/browser-pdf-converter-privacy'
    | '/blog/browser-tech-replacing-desktop-apps'
    | '/blog/compress-pdf-without-losing-quality'
    | '/blog/digital-document-workflow-students'
    | '/blog/excel-to-pdf-formatting-guide'
    | '/blog/freelance-contract-management-free'
    | '/blog/how-to-check-pdf-converter-safety'
    | '/blog/how-to-convert-images-to-pdf'
    | '/blog/how-to-convert-pdf-to-word'
    | '/blog/how-to-convert-webp-to-jpg'
    | '/blog/how-to-merge-pdf-files-online'
    | '/blog/how-to-resize-images-social-media'
    | '/blog/how-to-rotate-pdf-pages'
    | '/blog/how-to-split-pdf-pages'
    | '/blog/how-to-watermark-pdf-documents'
    | '/blog/how-to-watermark-photos-online'
    | '/blog/image-aspect-ratio-cropping-guide'
    | '/blog/jpg-vs-png-guide'
    | '/blog/pdf-vs-word-differences'
    | '/blog/risks-of-online-file-converters'
    | '/blog/text-to-pdf-converter-guide'
    | '/blog/webp-vs-jpg-vs-png'
    | '/blog/what-is-client-side-processing'
    | '/blog/why-compress-pdfs-for-email'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compress-image'
    | '/compress-pdf'
    | '/contact'
    | '/cookie'
    | '/crop-image'
    | '/disclaimer'
    | '/excel-to-pdf'
    | '/how-it-works'
    | '/jpg-to-pdf'
    | '/jpg-to-png'
    | '/merge-pdf'
    | '/mission'
    | '/pdf-to-jpg'
    | '/png-to-jpg'
    | '/privacy'
    | '/resize-image'
    | '/rotate-image'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/terms'
    | '/text-to-pdf'
    | '/watermark-image'
    | '/watermark-pdf'
    | '/webp-to-jpg'
    | '/blog/batch-image-processing-guide'
    | '/blog/best-free-pdf-tools'
    | '/blog/browser-pdf-converter-privacy'
    | '/blog/browser-tech-replacing-desktop-apps'
    | '/blog/compress-pdf-without-losing-quality'
    | '/blog/digital-document-workflow-students'
    | '/blog/excel-to-pdf-formatting-guide'
    | '/blog/freelance-contract-management-free'
    | '/blog/how-to-check-pdf-converter-safety'
    | '/blog/how-to-convert-images-to-pdf'
    | '/blog/how-to-convert-pdf-to-word'
    | '/blog/how-to-convert-webp-to-jpg'
    | '/blog/how-to-merge-pdf-files-online'
    | '/blog/how-to-resize-images-social-media'
    | '/blog/how-to-rotate-pdf-pages'
    | '/blog/how-to-split-pdf-pages'
    | '/blog/how-to-watermark-pdf-documents'
    | '/blog/how-to-watermark-photos-online'
    | '/blog/image-aspect-ratio-cropping-guide'
    | '/blog/jpg-vs-png-guide'
    | '/blog/pdf-vs-word-differences'
    | '/blog/risks-of-online-file-converters'
    | '/blog/text-to-pdf-converter-guide'
    | '/blog/webp-vs-jpg-vs-png'
    | '/blog/what-is-client-side-processing'
    | '/blog/why-compress-pdfs-for-email'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compress-image'
    | '/compress-pdf'
    | '/contact'
    | '/cookie'
    | '/crop-image'
    | '/disclaimer'
    | '/excel-to-pdf'
    | '/how-it-works'
    | '/jpg-to-pdf'
    | '/jpg-to-png'
    | '/merge-pdf'
    | '/mission'
    | '/pdf-to-jpg'
    | '/png-to-jpg'
    | '/privacy'
    | '/resize-image'
    | '/rotate-image'
    | '/rotate-pdf'
    | '/split-pdf'
    | '/terms'
    | '/text-to-pdf'
    | '/watermark-image'
    | '/watermark-pdf'
    | '/webp-to-jpg'
    | '/blog/batch-image-processing-guide'
    | '/blog/best-free-pdf-tools'
    | '/blog/browser-pdf-converter-privacy'
    | '/blog/browser-tech-replacing-desktop-apps'
    | '/blog/compress-pdf-without-losing-quality'
    | '/blog/digital-document-workflow-students'
    | '/blog/excel-to-pdf-formatting-guide'
    | '/blog/freelance-contract-management-free'
    | '/blog/how-to-check-pdf-converter-safety'
    | '/blog/how-to-convert-images-to-pdf'
    | '/blog/how-to-convert-pdf-to-word'
    | '/blog/how-to-convert-webp-to-jpg'
    | '/blog/how-to-merge-pdf-files-online'
    | '/blog/how-to-resize-images-social-media'
    | '/blog/how-to-rotate-pdf-pages'
    | '/blog/how-to-split-pdf-pages'
    | '/blog/how-to-watermark-pdf-documents'
    | '/blog/how-to-watermark-photos-online'
    | '/blog/image-aspect-ratio-cropping-guide'
    | '/blog/jpg-vs-png-guide'
    | '/blog/pdf-vs-word-differences'
    | '/blog/risks-of-online-file-converters'
    | '/blog/text-to-pdf-converter-guide'
    | '/blog/webp-vs-jpg-vs-png'
    | '/blog/what-is-client-side-processing'
    | '/blog/why-compress-pdfs-for-email'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompressImageRoute: typeof CompressImageRoute
  CompressPdfRoute: typeof CompressPdfRoute
  ContactRoute: typeof ContactRoute
  CookieRoute: typeof CookieRoute
  CropImageRoute: typeof CropImageRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ExcelToPdfRoute: typeof ExcelToPdfRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JpgToPdfRoute: typeof JpgToPdfRoute
  JpgToPngRoute: typeof JpgToPngRoute
  MergePdfRoute: typeof MergePdfRoute
  MissionRoute: typeof MissionRoute
  PdfToJpgRoute: typeof PdfToJpgRoute
  PngToJpgRoute: typeof PngToJpgRoute
  PrivacyRoute: typeof PrivacyRoute
  ResizeImageRoute: typeof ResizeImageRoute
  RotateImageRoute: typeof RotateImageRoute
  RotatePdfRoute: typeof RotatePdfRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TermsRoute: typeof TermsRoute
  TextToPdfRoute: typeof TextToPdfRoute
  WatermarkImageRoute: typeof WatermarkImageRoute
  WatermarkPdfRoute: typeof WatermarkPdfRoute
  WebpToJpgRoute: typeof WebpToJpgRoute
  BlogBatchImageProcessingGuideRoute: typeof BlogBatchImageProcessingGuideRoute
  BlogBestFreePdfToolsRoute: typeof BlogBestFreePdfToolsRoute
  BlogBrowserPdfConverterPrivacyRoute: typeof BlogBrowserPdfConverterPrivacyRoute
  BlogBrowserTechReplacingDesktopAppsRoute: typeof BlogBrowserTechReplacingDesktopAppsRoute
  BlogCompressPdfWithoutLosingQualityRoute: typeof BlogCompressPdfWithoutLosingQualityRoute
  BlogDigitalDocumentWorkflowStudentsRoute: typeof BlogDigitalDocumentWorkflowStudentsRoute
  BlogExcelToPdfFormattingGuideRoute: typeof BlogExcelToPdfFormattingGuideRoute
  BlogFreelanceContractManagementFreeRoute: typeof BlogFreelanceContractManagementFreeRoute
  BlogHowToCheckPdfConverterSafetyRoute: typeof BlogHowToCheckPdfConverterSafetyRoute
  BlogHowToConvertImagesToPdfRoute: typeof BlogHowToConvertImagesToPdfRoute
  BlogHowToConvertPdfToWordRoute: typeof BlogHowToConvertPdfToWordRoute
  BlogHowToConvertWebpToJpgRoute: typeof BlogHowToConvertWebpToJpgRoute
  BlogHowToMergePdfFilesOnlineRoute: typeof BlogHowToMergePdfFilesOnlineRoute
  BlogHowToResizeImagesSocialMediaRoute: typeof BlogHowToResizeImagesSocialMediaRoute
  BlogHowToRotatePdfPagesRoute: typeof BlogHowToRotatePdfPagesRoute
  BlogHowToSplitPdfPagesRoute: typeof BlogHowToSplitPdfPagesRoute
  BlogHowToWatermarkPdfDocumentsRoute: typeof BlogHowToWatermarkPdfDocumentsRoute
  BlogHowToWatermarkPhotosOnlineRoute: typeof BlogHowToWatermarkPhotosOnlineRoute
  BlogImageAspectRatioCroppingGuideRoute: typeof BlogImageAspectRatioCroppingGuideRoute
  BlogJpgVsPngGuideRoute: typeof BlogJpgVsPngGuideRoute
  BlogPdfVsWordDifferencesRoute: typeof BlogPdfVsWordDifferencesRoute
  BlogRisksOfOnlineFileConvertersRoute: typeof BlogRisksOfOnlineFileConvertersRoute
  BlogTextToPdfConverterGuideRoute: typeof BlogTextToPdfConverterGuideRoute
  BlogWebpVsJpgVsPngRoute: typeof BlogWebpVsJpgVsPngRoute
  BlogWhatIsClientSideProcessingRoute: typeof BlogWhatIsClientSideProcessingRoute
  BlogWhyCompressPdfsForEmailRoute: typeof BlogWhyCompressPdfsForEmailRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webp-to-jpg': {
      id: '/webp-to-jpg'
      path: '/webp-to-jpg'
      fullPath: '/webp-to-jpg'
      preLoaderRoute: typeof WebpToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark-pdf': {
      id: '/watermark-pdf'
      path: '/watermark-pdf'
      fullPath: '/watermark-pdf'
      preLoaderRoute: typeof WatermarkPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark-image': {
      id: '/watermark-image'
      path: '/watermark-image'
      fullPath: '/watermark-image'
      preLoaderRoute: typeof WatermarkImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-pdf': {
      id: '/text-to-pdf'
      path: '/text-to-pdf'
      fullPath: '/text-to-pdf'
      preLoaderRoute: typeof TextToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate-pdf': {
      id: '/rotate-pdf'
      path: '/rotate-pdf'
      fullPath: '/rotate-pdf'
      preLoaderRoute: typeof RotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate-image': {
      id: '/rotate-image'
      path: '/rotate-image'
      fullPath: '/rotate-image'
      preLoaderRoute: typeof RotateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize-image': {
      id: '/resize-image'
      path: '/resize-image'
      fullPath: '/resize-image'
      preLoaderRoute: typeof ResizeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-jpg': {
      id: '/png-to-jpg'
      path: '/png-to-jpg'
      fullPath: '/png-to-jpg'
      preLoaderRoute: typeof PngToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-jpg': {
      id: '/pdf-to-jpg'
      path: '/pdf-to-jpg'
      fullPath: '/pdf-to-jpg'
      preLoaderRoute: typeof PdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-png': {
      id: '/jpg-to-png'
      path: '/jpg-to-png'
      fullPath: '/jpg-to-png'
      preLoaderRoute: typeof JpgToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-pdf': {
      id: '/jpg-to-pdf'
      path: '/jpg-to-pdf'
      fullPath: '/jpg-to-pdf'
      preLoaderRoute: typeof JpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel-to-pdf': {
      id: '/excel-to-pdf'
      path: '/excel-to-pdf'
      fullPath: '/excel-to-pdf'
      preLoaderRoute: typeof ExcelToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-image': {
      id: '/crop-image'
      path: '/crop-image'
      fullPath: '/crop-image'
      preLoaderRoute: typeof CropImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-image': {
      id: '/compress-image'
      path: '/compress-image'
      fullPath: '/compress-image'
      preLoaderRoute: typeof CompressImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/why-compress-pdfs-for-email': {
      id: '/blog/why-compress-pdfs-for-email'
      path: '/blog/why-compress-pdfs-for-email'
      fullPath: '/blog/why-compress-pdfs-for-email'
      preLoaderRoute: typeof BlogWhyCompressPdfsForEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-client-side-processing': {
      id: '/blog/what-is-client-side-processing'
      path: '/blog/what-is-client-side-processing'
      fullPath: '/blog/what-is-client-side-processing'
      preLoaderRoute: typeof BlogWhatIsClientSideProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/webp-vs-jpg-vs-png': {
      id: '/blog/webp-vs-jpg-vs-png'
      path: '/blog/webp-vs-jpg-vs-png'
      fullPath: '/blog/webp-vs-jpg-vs-png'
      preLoaderRoute: typeof BlogWebpVsJpgVsPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/text-to-pdf-converter-guide': {
      id: '/blog/text-to-pdf-converter-guide'
      path: '/blog/text-to-pdf-converter-guide'
      fullPath: '/blog/text-to-pdf-converter-guide'
      preLoaderRoute: typeof BlogTextToPdfConverterGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/risks-of-online-file-converters': {
      id: '/blog/risks-of-online-file-converters'
      path: '/blog/risks-of-online-file-converters'
      fullPath: '/blog/risks-of-online-file-converters'
      preLoaderRoute: typeof BlogRisksOfOnlineFileConvertersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pdf-vs-word-differences': {
      id: '/blog/pdf-vs-word-differences'
      path: '/blog/pdf-vs-word-differences'
      fullPath: '/blog/pdf-vs-word-differences'
      preLoaderRoute: typeof BlogPdfVsWordDifferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jpg-vs-png-guide': {
      id: '/blog/jpg-vs-png-guide'
      path: '/blog/jpg-vs-png-guide'
      fullPath: '/blog/jpg-vs-png-guide'
      preLoaderRoute: typeof BlogJpgVsPngGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/image-aspect-ratio-cropping-guide': {
      id: '/blog/image-aspect-ratio-cropping-guide'
      path: '/blog/image-aspect-ratio-cropping-guide'
      fullPath: '/blog/image-aspect-ratio-cropping-guide'
      preLoaderRoute: typeof BlogImageAspectRatioCroppingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-watermark-photos-online': {
      id: '/blog/how-to-watermark-photos-online'
      path: '/blog/how-to-watermark-photos-online'
      fullPath: '/blog/how-to-watermark-photos-online'
      preLoaderRoute: typeof BlogHowToWatermarkPhotosOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-watermark-pdf-documents': {
      id: '/blog/how-to-watermark-pdf-documents'
      path: '/blog/how-to-watermark-pdf-documents'
      fullPath: '/blog/how-to-watermark-pdf-documents'
      preLoaderRoute: typeof BlogHowToWatermarkPdfDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-split-pdf-pages': {
      id: '/blog/how-to-split-pdf-pages'
      path: '/blog/how-to-split-pdf-pages'
      fullPath: '/blog/how-to-split-pdf-pages'
      preLoaderRoute: typeof BlogHowToSplitPdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-rotate-pdf-pages': {
      id: '/blog/how-to-rotate-pdf-pages'
      path: '/blog/how-to-rotate-pdf-pages'
      fullPath: '/blog/how-to-rotate-pdf-pages'
      preLoaderRoute: typeof BlogHowToRotatePdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-resize-images-social-media': {
      id: '/blog/how-to-resize-images-social-media'
      path: '/blog/how-to-resize-images-social-media'
      fullPath: '/blog/how-to-resize-images-social-media'
      preLoaderRoute: typeof BlogHowToResizeImagesSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-merge-pdf-files-online': {
      id: '/blog/how-to-merge-pdf-files-online'
      path: '/blog/how-to-merge-pdf-files-online'
      fullPath: '/blog/how-to-merge-pdf-files-online'
      preLoaderRoute: typeof BlogHowToMergePdfFilesOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-convert-webp-to-jpg': {
      id: '/blog/how-to-convert-webp-to-jpg'
      path: '/blog/how-to-convert-webp-to-jpg'
      fullPath: '/blog/how-to-convert-webp-to-jpg'
      preLoaderRoute: typeof BlogHowToConvertWebpToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-convert-pdf-to-word': {
      id: '/blog/how-to-convert-pdf-to-word'
      path: '/blog/how-to-convert-pdf-to-word'
      fullPath: '/blog/how-to-convert-pdf-to-word'
      preLoaderRoute: typeof BlogHowToConvertPdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-convert-images-to-pdf': {
      id: '/blog/how-to-convert-images-to-pdf'
      path: '/blog/how-to-convert-images-to-pdf'
      fullPath: '/blog/how-to-convert-images-to-pdf'
      preLoaderRoute: typeof BlogHowToConvertImagesToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-check-pdf-converter-safety': {
      id: '/blog/how-to-check-pdf-converter-safety'
      path: '/blog/how-to-check-pdf-converter-safety'
      fullPath: '/blog/how-to-check-pdf-converter-safety'
      preLoaderRoute: typeof BlogHowToCheckPdfConverterSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/freelance-contract-management-free': {
      id: '/blog/freelance-contract-management-free'
      path: '/blog/freelance-contract-management-free'
      fullPath: '/blog/freelance-contract-management-free'
      preLoaderRoute: typeof BlogFreelanceContractManagementFreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/excel-to-pdf-formatting-guide': {
      id: '/blog/excel-to-pdf-formatting-guide'
      path: '/blog/excel-to-pdf-formatting-guide'
      fullPath: '/blog/excel-to-pdf-formatting-guide'
      preLoaderRoute: typeof BlogExcelToPdfFormattingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/digital-document-workflow-students': {
      id: '/blog/digital-document-workflow-students'
      path: '/blog/digital-document-workflow-students'
      fullPath: '/blog/digital-document-workflow-students'
      preLoaderRoute: typeof BlogDigitalDocumentWorkflowStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/compress-pdf-without-losing-quality': {
      id: '/blog/compress-pdf-without-losing-quality'
      path: '/blog/compress-pdf-without-losing-quality'
      fullPath: '/blog/compress-pdf-without-losing-quality'
      preLoaderRoute: typeof BlogCompressPdfWithoutLosingQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/browser-tech-replacing-desktop-apps': {
      id: '/blog/browser-tech-replacing-desktop-apps'
      path: '/blog/browser-tech-replacing-desktop-apps'
      fullPath: '/blog/browser-tech-replacing-desktop-apps'
      preLoaderRoute: typeof BlogBrowserTechReplacingDesktopAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/browser-pdf-converter-privacy': {
      id: '/blog/browser-pdf-converter-privacy'
      path: '/blog/browser-pdf-converter-privacy'
      fullPath: '/blog/browser-pdf-converter-privacy'
      preLoaderRoute: typeof BlogBrowserPdfConverterPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/best-free-pdf-tools': {
      id: '/blog/best-free-pdf-tools'
      path: '/blog/best-free-pdf-tools'
      fullPath: '/blog/best-free-pdf-tools'
      preLoaderRoute: typeof BlogBestFreePdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/batch-image-processing-guide': {
      id: '/blog/batch-image-processing-guide'
      path: '/blog/batch-image-processing-guide'
      fullPath: '/blog/batch-image-processing-guide'
      preLoaderRoute: typeof BlogBatchImageProcessingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompressImageRoute: CompressImageRoute,
  CompressPdfRoute: CompressPdfRoute,
  ContactRoute: ContactRoute,
  CookieRoute: CookieRoute,
  CropImageRoute: CropImageRoute,
  DisclaimerRoute: DisclaimerRoute,
  ExcelToPdfRoute: ExcelToPdfRoute,
  HowItWorksRoute: HowItWorksRoute,
  JpgToPdfRoute: JpgToPdfRoute,
  JpgToPngRoute: JpgToPngRoute,
  MergePdfRoute: MergePdfRoute,
  MissionRoute: MissionRoute,
  PdfToJpgRoute: PdfToJpgRoute,
  PngToJpgRoute: PngToJpgRoute,
  PrivacyRoute: PrivacyRoute,
  ResizeImageRoute: ResizeImageRoute,
  RotateImageRoute: RotateImageRoute,
  RotatePdfRoute: RotatePdfRoute,
  SplitPdfRoute: SplitPdfRoute,
  TermsRoute: TermsRoute,
  TextToPdfRoute: TextToPdfRoute,
  WatermarkImageRoute: WatermarkImageRoute,
  WatermarkPdfRoute: WatermarkPdfRoute,
  WebpToJpgRoute: WebpToJpgRoute,
  BlogBatchImageProcessingGuideRoute: BlogBatchImageProcessingGuideRoute,
  BlogBestFreePdfToolsRoute: BlogBestFreePdfToolsRoute,
  BlogBrowserPdfConverterPrivacyRoute: BlogBrowserPdfConverterPrivacyRoute,
  BlogBrowserTechReplacingDesktopAppsRoute:
    BlogBrowserTechReplacingDesktopAppsRoute,
  BlogCompressPdfWithoutLosingQualityRoute:
    BlogCompressPdfWithoutLosingQualityRoute,
  BlogDigitalDocumentWorkflowStudentsRoute:
    BlogDigitalDocumentWorkflowStudentsRoute,
  BlogExcelToPdfFormattingGuideRoute: BlogExcelToPdfFormattingGuideRoute,
  BlogFreelanceContractManagementFreeRoute:
    BlogFreelanceContractManagementFreeRoute,
  BlogHowToCheckPdfConverterSafetyRoute: BlogHowToCheckPdfConverterSafetyRoute,
  BlogHowToConvertImagesToPdfRoute: BlogHowToConvertImagesToPdfRoute,
  BlogHowToConvertPdfToWordRoute: BlogHowToConvertPdfToWordRoute,
  BlogHowToConvertWebpToJpgRoute: BlogHowToConvertWebpToJpgRoute,
  BlogHowToMergePdfFilesOnlineRoute: BlogHowToMergePdfFilesOnlineRoute,
  BlogHowToResizeImagesSocialMediaRoute: BlogHowToResizeImagesSocialMediaRoute,
  BlogHowToRotatePdfPagesRoute: BlogHowToRotatePdfPagesRoute,
  BlogHowToSplitPdfPagesRoute: BlogHowToSplitPdfPagesRoute,
  BlogHowToWatermarkPdfDocumentsRoute: BlogHowToWatermarkPdfDocumentsRoute,
  BlogHowToWatermarkPhotosOnlineRoute: BlogHowToWatermarkPhotosOnlineRoute,
  BlogImageAspectRatioCroppingGuideRoute:
    BlogImageAspectRatioCroppingGuideRoute,
  BlogJpgVsPngGuideRoute: BlogJpgVsPngGuideRoute,
  BlogPdfVsWordDifferencesRoute: BlogPdfVsWordDifferencesRoute,
  BlogRisksOfOnlineFileConvertersRoute: BlogRisksOfOnlineFileConvertersRoute,
  BlogTextToPdfConverterGuideRoute: BlogTextToPdfConverterGuideRoute,
  BlogWebpVsJpgVsPngRoute: BlogWebpVsJpgVsPngRoute,
  BlogWhatIsClientSideProcessingRoute: BlogWhatIsClientSideProcessingRoute,
  BlogWhyCompressPdfsForEmailRoute: BlogWhyCompressPdfsForEmailRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
